import React from "react";
import Sidebar from "../Sidebar";
import styles from "../Dashboard.module.css";
import MUITable from "../generic/MUITable";
import { randomId } from "@mui/x-data-grid-generator";
const Sapatos = () => {
  const mRows = [
    {
      id: randomId(),
      Referencia: 0,
      PrecoVenda: "567.85",
      Nome: "bertimings",
      Descricao: "miccopriuos",
      Marca: "wrarora",
      Tamanho: 682,
      QuantidadeEstoque: 307,
    },
    {
      id: randomId(),
      Referencia: 1,
      PrecoVenda: "439.06",
      Nome: "nookayergs",
      Descricao: "procody",
      Marca: "zhever",
      Tamanho: 152,
      QuantidadeEstoque: 936,
    },
    {
      id: randomId(),
      Referencia: 2,
      PrecoVenda: "847.34",
      Nome: "hygienevangelist",
      Descricao: "adliarvertiang",
      Marca: "slacnard",
      Tamanho: 67,
      QuantidadeEstoque: 239,
    },
    {
      id: randomId(),
      Referencia: 3,
      PrecoVenda: "293.84",
      Nome: "caticlasurghts",
      Descricao: "posical",
      Marca: "zumond",
      Tamanho: 930,
      QuantidadeEstoque: 943,
    },
    {
      id: randomId(),
      Referencia: 4,
      PrecoVenda: "483.00",
      Nome: "untrimattacks",
      Descricao: "ixcent",
      Marca: "seset",
      Tamanho: 262,
      QuantidadeEstoque: 252,
    },
    {
      id: randomId(),
      Referencia: 5,
      PrecoVenda: "234.89",
      Nome: "huzlip",
      Descricao: "wheablist",
      Marca: "atreim",
      Tamanho: 756,
      QuantidadeEstoque: 227,
    },
    {
      id: randomId(),
      Referencia: 6,
      PrecoVenda: "170.77",
      Nome: "strizzes",
      Descricao: "boopular",
      Marca: "qok",
      Tamanho: 51,
      QuantidadeEstoque: 639,
    },
    {
      id: randomId(),
      Referencia: 7,
      PrecoVenda: "961.56",
      Nome: "jobfusticate",
      Descricao: "befolking",
      Marca: "khando",
      Tamanho: 182,
      QuantidadeEstoque: 156,
    },
    {
      id: randomId(),
      Referencia: 8,
      PrecoVenda: "732.43",
      Nome: "pulate",
      Descricao: "wireve",
      Marca: "ensby",
      Tamanho: 993,
      QuantidadeEstoque: 946,
    },
    {
      id: randomId(),
      Referencia: 9,
      PrecoVenda: "733.69",
      Nome: "accurry",
      Descricao: "opcong",
      Marca: "iamont",
      Tamanho: 936,
      QuantidadeEstoque: 966,
    },
    {
      id: randomId(),
      Referencia: 10,
      PrecoVenda: "866.01",
      Nome: "oleald",
      Descricao: "impenelly",
      Marca: "morset",
      Tamanho: 214,
      QuantidadeEstoque: 38,
    },
    {
      id: randomId(),
      Referencia: 11,
      PrecoVenda: "353.85",
      Nome: "blassuing",
      Descricao: "aquaked",
      Marca: "heuridge",
      Tamanho: 405,
      QuantidadeEstoque: 807,
    },
    {
      id: randomId(),
      Referencia: 12,
      PrecoVenda: "933.52",
      Nome: "forciner",
      Descricao: "franchans",
      Marca: "vlading",
      Tamanho: 660,
      QuantidadeEstoque: 304,
    },
    {
      id: randomId(),
      Referencia: 13,
      PrecoVenda: "154.24",
      Nome: "rosion",
      Descricao: "arkets",
      Marca: "drosas",
      Tamanho: 617,
      QuantidadeEstoque: 337,
    },
    {
      id: randomId(),
      Referencia: 14,
      PrecoVenda: "1175.45",
      Nome: "wortunde",
      Descricao: "arinterpord",
      Marca: "zhohsas",
      Tamanho: 972,
      QuantidadeEstoque: 853,
    },
    {
      id: randomId(),
      Referencia: 15,
      PrecoVenda: "1297.01",
      Nome: "gingthy",
      Descricao: "furnicallment",
      Marca: "jarc",
      Tamanho: 80,
      QuantidadeEstoque: 698,
    },
    {
      id: randomId(),
      Referencia: 16,
      PrecoVenda: "1315.73",
      Nome: "iniquin",
      Descricao: "taindust",
      Marca: "blido",
      Tamanho: 114,
      QuantidadeEstoque: 140,
    },
    {
      id: randomId(),
      Referencia: 17,
      PrecoVenda: "1114.99",
      Nome: "auspectress",
      Descricao: "putocrypes",
      Marca: "voni",
      Tamanho: 395,
      QuantidadeEstoque: 344,
    },
    {
      id: randomId(),
      Referencia: 18,
      PrecoVenda: "1408.51",
      Nome: "baxtoy",
      Descricao: "fouralier",
      Marca: "ensgas",
      Tamanho: 12,
      QuantidadeEstoque: 588,
    },
    {
      id: randomId(),
      Referencia: 19,
      PrecoVenda: "1117.25",
      Nome: "vituenize",
      Descricao: "supernstic",
      Marca: "ockham",
      Tamanho: 893,
      QuantidadeEstoque: 713,
    },
    {
      id: randomId(),
      Referencia: 20,
      PrecoVenda: "877.54",
      Nome: "dorizating",
      Descricao: "eefullanizess",
      Marca: "eyrihport",
      Tamanho: 187,
      QuantidadeEstoque: 950,
    },
    {
      id: randomId(),
      Referencia: 21,
      PrecoVenda: "929.06",
      Nome: "madeliatize",
      Descricao: "surogou",
      Marca: "yribus",
      Tamanho: 349,
      QuantidadeEstoque: 780,
    },
    {
      id: randomId(),
      Referencia: 22,
      PrecoVenda: "1343.63",
      Nome: "dominitoxing",
      Descricao: "chershoee",
      Marca: "zlougow",
      Tamanho: 411,
      QuantidadeEstoque: 478,
    },
    {
      id: randomId(),
      Referencia: 23,
      PrecoVenda: "1131.03",
      Nome: "evolissuppoint",
      Descricao: "propericitess",
      Marca: "phefast",
      Tamanho: 31,
      QuantidadeEstoque: 10,
    },
    {
      id: randomId(),
      Referencia: 24,
      PrecoVenda: "110.33",
      Nome: "slation",
      Descricao: "prologisang",
      Marca: "wrafast",
      Tamanho: 359,
      QuantidadeEstoque: 995,
    },
    {
      id: randomId(),
      Referencia: 25,
      PrecoVenda: "1254.83",
      Nome: "ception",
      Descricao: "eaterfully",
      Marca: "wria",
      Tamanho: 404,
      QuantidadeEstoque: 848,
    },
    {
      id: randomId(),
      Referencia: 26,
      PrecoVenda: "1023.50",
      Nome: "alogiced",
      Descricao: "faminoces",
      Marca: "wester",
      Tamanho: 849,
      QuantidadeEstoque: 583,
    },
    {
      id: randomId(),
      Referencia: 27,
      PrecoVenda: "314.20",
      Nome: "resochocodmaid",
      Descricao: "proationizes",
      Marca: "prurg",
      Tamanho: 913,
      QuantidadeEstoque: 706,
    },
    {
      id: randomId(),
      Referencia: 28,
      PrecoVenda: "1094.82",
      Nome: "ausceigh",
      Descricao: "modecarlialing",
      Marca: "eypus",
      Tamanho: 515,
      QuantidadeEstoque: 854,
    },
    {
      id: randomId(),
      Referencia: 29,
      PrecoVenda: "1423.12",
      Nome: "cherlormur",
      Descricao: "sepezz",
      Marca: "ordmery",
      Tamanho: 803,
      QuantidadeEstoque: 264,
    },
    {
      id: randomId(),
      Referencia: 30,
      PrecoVenda: "1188.13",
      Nome: "ravicted",
      Descricao: "nianglors",
      Marca: "kroland",
      Tamanho: 282,
      QuantidadeEstoque: 913,
    },
    {
      id: randomId(),
      Referencia: 31,
      PrecoVenda: "1377.51",
      Nome: "noxu",
      Descricao: "refurn",
      Marca: "drecburgh",
      Tamanho: 227,
      QuantidadeEstoque: 318,
    },
    {
      id: randomId(),
      Referencia: 32,
      PrecoVenda: "998.84",
      Nome: "anitisrammist",
      Descricao: "shizzo",
      Marca: "yheridge",
      Tamanho: 433,
      QuantidadeEstoque: 884,
    },
    {
      id: randomId(),
      Referencia: 33,
      PrecoVenda: "1114.36",
      Nome: "unreasto",
      Descricao: "oppred",
      Marca: "dolas",
      Tamanho: 967,
      QuantidadeEstoque: 597,
    },
    {
      id: randomId(),
      Referencia: 34,
      PrecoVenda: "948.98",
      Nome: "thrubbish",
      Descricao: "boycher",
      Marca: "zhaaver",
      Tamanho: 607,
      QuantidadeEstoque: 825,
    },
    {
      id: randomId(),
      Referencia: 35,
      PrecoVenda: "461.58",
      Nome: "heavinted",
      Descricao: "hureaddiss",
      Marca: "dedo",
      Tamanho: 730,
      QuantidadeEstoque: 161,
    },
    {
      id: randomId(),
      Referencia: 36,
      PrecoVenda: "770.45",
      Nome: "puffalope",
      Descricao: "diffetruction",
      Marca: "crury",
      Tamanho: 855,
      QuantidadeEstoque: 451,
    },
    {
      id: randomId(),
      Referencia: 37,
      PrecoVenda: "230.97",
      Nome: "tation",
      Descricao: "advoter",
      Marca: "ustrane",
      Tamanho: 550,
      QuantidadeEstoque: 824,
    },
    {
      id: randomId(),
      Referencia: 38,
      PrecoVenda: "286.97",
      Nome: "requirtion",
      Descricao: "soniting",
      Marca: "olntin",
      Tamanho: 123,
      QuantidadeEstoque: 862,
    },
    {
      id: randomId(),
      Referencia: 39,
      PrecoVenda: "1226.38",
      Nome: "supernstic",
      Descricao: "bryanklets",
      Marca: "ardmouth",
      Tamanho: 47,
      QuantidadeEstoque: 296,
    },
    {
      id: randomId(),
      Referencia: 40,
      PrecoVenda: "247.35",
      Nome: "litifactrones",
      Descricao: "oppoosedgetal",
      Marca: "xeymouth",
      Tamanho: 771,
      QuantidadeEstoque: 581,
    },
    {
      id: randomId(),
      Referencia: 41,
      PrecoVenda: "621.58",
      Nome: "gerrickle",
      Descricao: "mothodchront",
      Marca: "wiham",
      Tamanho: 598,
      QuantidadeEstoque: 200,
    },
    {
      id: randomId(),
      Referencia: 42,
      PrecoVenda: "1358.24",
      Nome: "imsomed",
      Descricao: "hevephiny",
      Marca: "wuginia",
      Tamanho: 20,
      QuantidadeEstoque: 876,
    },
    {
      id: randomId(),
      Referencia: 43,
      PrecoVenda: "745.46",
      Nome: "laritione",
      Descricao: "iniquin",
      Marca: "klusall",
      Tamanho: 42,
      QuantidadeEstoque: 678,
    },
    {
      id: randomId(),
      Referencia: 44,
      PrecoVenda: "335.75",
      Nome: "pricenano",
      Descricao: "recepteds",
      Marca: "drunbury",
      Tamanho: 271,
      QuantidadeEstoque: 148,
    },
    {
      id: randomId(),
      Referencia: 45,
      PrecoVenda: "1289.32",
      Nome: "collerescapts",
      Descricao: "thresyncess",
      Marca: "yurgh",
      Tamanho: 563,
      QuantidadeEstoque: 704,
    },
    {
      id: randomId(),
      Referencia: 46,
      PrecoVenda: "860.36",
      Nome: "knealineuring",
      Descricao: "coopicals",
      Marca: "graso",
      Tamanho: 529,
      QuantidadeEstoque: 635,
    },
    {
      id: randomId(),
      Referencia: 47,
      PrecoVenda: "840.19",
      Nome: "suffergod",
      Descricao: "mediviction",
      Marca: "clerton",
      Tamanho: 653,
      QuantidadeEstoque: 554,
    },
    {
      id: randomId(),
      Referencia: 48,
      PrecoVenda: "501.24",
      Nome: "duzafizz",
      Descricao: "catterful",
      Marca: "arcridge",
      Tamanho: 83,
      QuantidadeEstoque: 873,
    },
    {
      id: randomId(),
      Referencia: 49,
      PrecoVenda: "604.10",
      Nome: "tweirshing",
      Descricao: "frorealm",
      Marca: "anceson",
      Tamanho: 979,
      QuantidadeEstoque: 290,
    },
  ];

  const mColumns = [
    {
      field: "Referencia",
      headerName: "Referencia",
      width: 90,
      editable: true,
    },
    {
      field: "PrecoVenda",
      headerName: "Preço Venda",
      type: "number",
      width: 180,
      editable: true,
    },
    {
      field: "Nome",
      headerName: "Nome",
      width: 180,
      editable: true,
    },
    {
      field: "Descricao",
      headerName: "Descrição",
      type: "date",
      width: 300,
      editable: true,
    },
    {
      field: "Marca",
      headerName: "Marca",
      type: "string",
      width: 180,
      editable: true,
    },
    {
      field: "Tamanho",
      headerName: "Tamanho",
      type: "number",
      width: 180,
      editable: true,
    },
    {
      field: "QuantidadeEstoque",
      headerName: "Quantidade Estoque",
      type: "string",
      editable: true,
    },
  ];

  return (
    <div className={styles.dashboardOther}>
      <Sidebar />
      <MUITable rows={mRows} columns={mColumns} />
    </div>
  );
};

export default Sapatos;
